version = "2"

[linters]
enable = [
    "gosec",
    "govet",
]

[linters.settings.govet]
enable = [
    "fieldalignment",
]

[linters.exclusions]
presets = [
    "std-error-handling",
]

[formatters]
enable = [
    "golines",
    "goimports",
]
